services:
  tvcc:
    container_name: tvcc
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/tvcc
    working_dir: /tvcc
    command: ./test.sh
    cap_add: 
      - SYS_PTRACE
    security_opt: 
      - seccomp=unconfined
